spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  data:
    mongodb:
      uri: mongodb://localhost:27017/dummy
management:
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP
  info:
    git:
      mode: full
  context-path: /actuators

upload:
  path: E:\logs\